#!/bin/sh

git rm -qr dist/*
./node_modules/.bin/grunt clean build
git add dist && git commit -m "Deploy `date -u`"
git remote show | grep heroku || git remote add heroku git@heroku.com:neui.git
git subtree push --prefix dist heroku master
